controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint1_head
      - joint2_rotor

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    gains:
      joint1_head:
        p: 80.0
        i: 0.01
        d: 8.0
        i_clamp_max:  1.0
        i_clamp_min: -1.0
      joint2_rotor:
        p: 40.0
        i: 0.005
        d: 4.0
        i_clamp_max:  0.5
        i_clamp_min: -0.5

    constraints:
      goal_time: 5.0
      joint1_head:
        goal: 0.05
      joint2_rotor:
        goal: 0.05

    open_loop_control: false
    allow_partial_joints_goal: false